### ISSUE TITLE
Ability to silence the concierge

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium-concierge#108]
There may be scenarios where we want the concierge to disengage from all or part of a PR/issue, e.g., perhaps if there is a PR we want to keep open and not merge for a few months.

Some experience here will probably make what is useful obvious, but I could imagine something like an `@mention` or tasklist checkbox to be able to silence things like the stale bumper, CHANGES.md update, etc.

**Comment by OmarShehata** [comment]
This is implemented in the bumper script (https://github.com/AnalyticalGraphicsInc/cesium-concierge/pull/106). Just needs to be generalized (https://github.com/AnalyticalGraphicsInc/cesium-concierge/issues/110).
