### ISSUE TITLE
Stale PR bumper broken again

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium-concierge#116]
Last time I looked at this the cron script wasn't running because of windows line endings. I confirmed and fixed this locally by running it in Docker on my machine. I think when it pushed/redeployed it got the wrong line endings again. 

This should be an easy fix.

**Comment by OmarShehata** [comment]
Two more problems: 

* The environment variables in the file must not have spaces between the ` = `.
* Grabbing the environment variables with `. file` does not work when the variables have dashes in between, since that's not a valid variable name (but github repo's have dashes). Apparently you can work around this by setting them by `env "$(cat /var/app/sample_env)"` instead.

**Comment by ggetz** [comment]
Is another solution beyond cron jobs worth looking into?

**Comment by OmarShehata** [comment]
This actually, finally works now!
