### ISSUE TITLE
Add `signature` parameter to `commentOnClosedIssue`

### ISSUE THREAD

**Issue by omh1280** [AnalyticalGraphicsInc/cesium-concierge#18]
Add a way to customize the message sent from `commentOnClosedIssue`. In its basic form, this would be a `string` which prepends the list of comments to update. If we want to be more fancy, it could be a callback which formats an array of links into a string.

**Comment by mramato** [comment]
This should be one signature configuration for all bot comments, not just for `commentOnClosedIssue`
