### ISSUE TITLE
New pull request bot support

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium-concierge#25]
Add a webhook for all new PRs that does the following:

1. If CHANGES.md has not been updated, ask the user if it needs to be updated (it may not be so phrasing is important here).  Make this message configurable.
2. ThirdParty support
   a. Add a configuration that is a list of `ThirdParty` folders (differs per repository).
   b. If there is a new or updated file in tone of the ``ThirdParty` folders, add a comment mentioning that it has been changed/added and ask whether an update to License information is needed.
3. CLA check (we probably want to hold off on this and handle it in a separate PR).

**Comment by omh1280** [comment]
- [x] If CHANGES.md has not been updated, ask the user if it needs to be updated (it may not be so phrasing is important here). Make this message configurable.
- [x] ThirdParty support
- [ ] CLA check

**Comment by mramato** [comment]
Fixed in #69
