### ISSUE TITLE
2 configurable times for bumping PR's

### ISSUE THREAD

**Issue by omh1280** [AnalyticalGraphicsInc/cesium-concierge#55]
It would be nice to have two different, configurable `maxDaysSinceUpdate` times:
- One would specify the _initial_ time after a PR is stale to bump it
- The other would specify the _second_ (or more) times after it has already been bumped to comment again

**Comment by pjcozzi** [comment]
@OmarShehata is this still needed?  Maybe not?

**Comment by OmarShehata** [comment]
I think it's too fine grained for what we need right now.

**Comment by pjcozzi** [comment]
OK, can someone with commit access please close then?
