### ISSUE TITLE
The bot shouldn't tell me to post on the forum when I'm telling a user to post on the forum

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium-concierge#61]
https://github.com/AnalyticalGraphicsInc/cesium/issues/5742#issuecomment-322162603

**Comment by pjcozzi** [comment]
Good catch!

**Comment by mramato** [comment]
The problem is the current regex checks for any google groups link, (even non-cesium-dev ones).  The regex needs to be updated to only look at actual message, which could be tricky because query parameters can be in any order.

**Comment by hpinkos** [comment]
Can we use `queryToObject` to see if msg is in the query string?

**Comment by mramato** [comment]
I think it's actually part of the hash, not the query string.  This should be totally doable with a modified regex either way.
