### ISSUE TITLE
Stale PR bumper only gets first 30 PRs

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium-concierge#70]
The GitHub API only returns the first 30 pull requests and requires you to use pagination to make additional requests.  The bumper code does not currently do this, so it only looks at the 30 newest pull requests (and unfortunately, Cesium has more than 30 open PRs most of the time).

**Comment by OmarShehata** [comment]
Fixed by https://github.com/AnalyticalGraphicsInc/cesium-concierge/pull/106
