### ISSUE TITLE
Easier to see status at a glance

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium-concierge#78]
Take a look at how some other bots label CLA status.  They aren't always as verbose as ours, and usually they have some sort of visual status indicator (label or otherwise) so you can just glance at it and see what's going on.  Here's Khronos:

![samplekhronoscla](https://user-images.githubusercontent.com/1235080/30328813-758cf6b0-979e-11e7-9ffa-fa6ee9c9d0d2.png)

I don't want to create real issue links here, but I'll provide the URL for reference:

`https://github.com/KhronosGroup/glTF-Validator/pull/18`

Microsoft uses actual GitHub labels for this:

![samplemicrosoftcla](https://user-images.githubusercontent.com/1235080/30328894-b9ecfb16-979e-11e7-85a6-28f55a33d512.png)

`https://github.com/Microsoft/vscode/pull/34042`

In fact, for PRs from people that already have CLAs on file, the bot doesn't speak up at all, it just slaps the label on and calls it a day:

![samplemicrosoftalreadycla](https://user-images.githubusercontent.com/1235080/30328991-07048b94-979f-11e7-94ee-8328d2d4b1ae.png)

`https://github.com/Microsoft/vscode/pull/33986`

Our current implementation makes people read and re-read the same boilerplate text across multiple PRs just to see which ones have CLAs and which ones need CLAs.  It would be nice to have a more visual status indicator, to avoid the need to re-read the bot's text carefully each time.

**Comment by ggetz** [comment]
Labeling is still up in the air as we'd need to give the bot write access to the repo, but I like the visual indicators a lot, and it would be easy to update the template to include them.

**Comment by emackey** [comment]
![https://img.shields.io/badge/CLA-signed-brightgreen.svg](https://img.shields.io/badge/CLA-signed-brightgreen.svg)

```
![https://img.shields.io/badge/CLA-signed-brightgreen.svg](https://img.shields.io/badge/CLA-signed-brightgreen.svg)
```

![https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla](https://img.shields.io/badge/CLA-required-red.svg)

```
![https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla](https://img.shields.io/badge/CLA-required-red.svg)
```

Or of you don't want red:

![https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla](https://img.shields.io/badge/CLA-required-yellow.svg)

```
![https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla](https://img.shields.io/badge/CLA-required-yellow.svg)
```

**Comment by emackey** [comment]
![Signed CLA is on file.](https://img.shields.io/badge/CLA-signed-brightgreen.svg)

```
![Signed CLA is on file.](https://img.shields.io/badge/CLA-signed-brightgreen.svg)
```

[![Please sign the CLA before we review this PR.](https://img.shields.io/badge/CLA-required-red.svg)](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)

```
[![Please sign the CLA before we review this PR.](https://img.shields.io/badge/CLA-required-red.svg)](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)
```

Or of you don't want red:

[![Please sign the CLA before we review this PR.](https://img.shields.io/badge/CLA-required-yellow.svg)](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)

```
[![Please sign the CLA before we review this PR.](https://img.shields.io/badge/CLA-required-yellow.svg)](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)
```

**Comment by ggetz** [comment]
This is now configurable at the repo level. The visual indicator were added to cesium in [this PR](https://github.com/AnalyticalGraphicsInc/cesium/pull/5937).
