### ISSUE TITLE
Replace concatenated paragraphs with bullets and icons in auto comments

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium-concierge#83]
The concierge will provide a useful message like:

> Welcome to the Cesium community @nice-contributor
>
>Can you please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) so that we can review and merge this pull request?
>
> I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

This would be slightly more readable and fun if each paragraph was a bullet (or maybe a table) that had a check or X (or something more friendly than an X).  I've seen other bots (maybe from Apple or Google) like this.

**Comment by ggetz** [comment]
Related #78

**Comment by OmarShehata** [comment]
Done with https://github.com/AnalyticalGraphicsInc/cesium-concierge/pull/111 !
