### ISSUE TITLE
Comment if unit tests were not added/updates

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium-concierge#92]
It's imperfect, but it would be useful to ask if a unit test should be added if no files in the `Specs` directory changed.

**Comment by OmarShehata** [comment]
This would be easy to do, but I think it would make a much bigger impact if concierge/travis could run the code coverage test, and could actually warn you for sure when your PR decreases the coverage, and asks you to fix that. 

@ggetz what do you think?

**Comment by ggetz** [comment]
@OmarShehata I think coverage as part of CI would take a while to build when the process is already pretty long. I think it'd be useful, so open a separate issue, but I think that's too big to cover presently.

**Comment by OmarShehata** [comment]
This is done!
